services:
  airflow-webserver:
    #image: apache/airflow:2.9.1
    #build: .
    image: mensajeria-airflow-image
    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-scheduler
    environment:
      - PYTHONPATH=/opt/airflow/etl_app
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@host.docker.internal:5432/airflow
      - AIRFLOW__WEBSERVER__RBAC=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl_app:/opt/airflow/etl_app
      - ./backups:/opt/airflow/backups
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    #image: apache/airflow:2.9.1
    #build: .
    image: mensajeria-airflow-image
    container_name: airflow-scheduler
    restart: always
    environment:
      - PYTHONPATH=/opt/airflow/etl_app
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@host.docker.internal:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl_app:/opt/airflow/etl_app
      - ./backups:/opt/airflow/backups
    command: scheduler

  airflow-init:
    #image: apache/airflow:2.9.1
    #build: .
    image: mensajeria-airflow-image
    container_name: airflow-init
    environment:
      - PYTHONPATH=/opt/airflow/etl_app
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@host.docker.internal:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl_app:/opt/airflow/etl_app
      - ./backups:/opt/airflow/backups
    entrypoint: >
      bash -c "
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com
      "
